apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 087748863544.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 087748863544.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: bb032032
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
